### ISSUE TITLE
Video never plays

### ISSUE THREAD

**Issue by s3than** [paulbhartzog/ubersicht-video-widget#1]
Running latest versions OSX 10.11.4 sample video doesn't load.

**Comment by paulbhartzog** [comment]
Thx for the note.

In the example (in README.md), the folder that the movie is in is called "movie.widget" and in the .coffee file it is called "video.widget" and when you actually install this from the zip then the folder ends up being called "ubersicht-video-widget.widget".

The point is that you can name the folder whatever you want as long as the .coffee file has the correct path.  Please let me know if you have a correct path and it still doesn't work. :-)

**Comment by tristan-k** [comment]
I adjusted the path properly but uebersicht just shows a still frame of the video. Also: How to make the video the size of your entire desktop and have it work like a desktop wallpaper (like mentioned in the readme)?

![ishot-001](https://cloud.githubusercontent.com/assets/732025/26104814/c617c9aa-3a3f-11e7-8de2-e8043d129f99.jpg)

**Comment by borgendorf** [comment]
To make a video play as a desktop background, I use the following settings. The biggest changes are removing "controls" and adding "loop" and "autoplay". You'll need to adjust your height number to match your monitor, and you may also need to adjust the top: number in the style section. 

```

render: ->"""
  <video height="1692" loop autoplay> 
    <source src="ubersicht-video-widget.widget/silentwatchercampfire1080p.mp4" type="video/mp4">
    Your browser does not support the video tag.
  </video>
"""

style: """
  position: absolute
  top: 0px
  left: 0px
  border: 1px solid #000
  z-index: -1
  /* kluge to erase space at bottom of video inside container */
  video
    margin-bottom: -4px
"""

```
